### ISSUE TITLE
SDK10: Splash screen not working

### ISSUE THREAD

**Issue by Vaibhav-Takeda** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#580] opened 2022-03-16 10:12 UTC
Hi Team,

I have updated from SDK 8.3 to SDK10 in my cordova project but splash screen does not seem to be working in iOS.

I have also tried creating a blank hybrid_local project with forcehybrid library. When I launch the app, a black screen is displayed followed by a white screen, followed by login screen.

Could you please look into this and fix this in next upcoming release. We want to update to SDK10 for 2 of our clients.

@wmathurin @bhariharan

**Comment by wmathurin** [comment] 2022-04-04 23:29
This is a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/539

**Comment by va1bhav** [comment] 2022-04-05 03:38
@wmathurin I don't believe #539 and this issue are same since, they are using some third party library due to which they are unable to proceed past the splash screen.

However, my app works perfectly other than being able to view the splash screen. Could you please validate? Thank you!

**Comment by gkotula** [comment] 2022-08-30 20:19
Hi @va1bhav I just created a `forcehybrid` app for iOS using v10.1.1 (latest as of writing this) and ran it on iOS simulator 15.5, and I did not observe the black screen you're describing.  Could you confirm whether updating to this SDK version fixes the issue for you?  Thanks!

**Comment by gkotula** [comment] 2022-11-28 20:36
Closing due to lack of response.

**Closed by gkotula** 2022-11-28 20:36 UTC
