### ISSUE TITLE
Hybrid Remote app Can't redirect to visualforce page after loging In (iOS)

### ISSUE THREAD

**Issue by ny1014** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#560] opened 2021-10-20 00:21 UTC
Version of Mobile SDK Used: v9.1.1
Issue found in Native App or Hybrid App: Hybrid Remote App
OS Version:14.4
Device:iphone 12
Steps to reproduce:1.Using the native browser for user authentication on iOS 2.login by custom domain,3 Single Sign On -->white page
Expected Behavior:redirect to visualforce page
Error Log:
2021-10-19 19:21:44.635728+0900 bankneo_lwcapp[4954:19987068] [SalesforceHybrid] CLASS: SFHybridViewController webView:decidePolicyForNavigationAction:decisionHandler: Loading URL 'https://xxxxxx.salesforce.com/secur/frontdoor.jsp?sid=[redacted]&retURL=https%3A%2F%2Fxxxxxxxx.my.salesforce.com%2Fapex%2Fxxxxxxxx&display=touch'
2021-10-19 19:21:44.635854+0900 bankneo_lwcapp[4954:19987068] [SalesforceHybrid] CLASS: SFHybridViewController Caught login redirect from session timeout. Reauthenticating.

9.bootconfig.json:
{
"remoteAccessConsumerKey": "3MVG95mg0lk4bathqh1CPVfV_V5chA8pCpHhWeUmGW2anfYdl7.rdnpH1C7tNaD.B3EhFwiXkW0ay_QX.tvDe",
"oauthRedirectURI": "LWCSSO:///mobilesdk/detect/oauth/done",
"oauthScopes": ["web", "api"],
"isLocal": false,
"startPage": "apex/myVFPage",
"errorPage": "error.html",
"shouldAuthenticate": true,
"attemptOfflineLoad": false,
"androidPushNotificationClientId": ""
}

**Comment by wmathurin** [comment] 2021-11-04 01:06
It looks like this is a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/560. So closing.

**Closed by wmathurin** 2021-11-04 01:06 UTC
