### ISSUE TITLE
SDK 7.0 iOS Authentication flow

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#437] opened 2019-01-16 07:11 UTC
Cordova version : 8.1.2
SDK version : 7.0.0

App description:
I have updated my hybrid app from SDK 6.2 to SDK 7.0.
My app declares "shouldAuthenticate": false in bootconfig.json and calls the login() method from force.js when required.

Issue:
Upon launching the app, it is getting redirected to login screen regardless of declaration in bootconfig.json.

**Comment by wmathurin** [comment] 2019-01-16 22:14
It looks like a regression. We will look into it.

**Comment by trooper2013** [comment] 2019-01-17 00:53
@va1bhav Open up UIApplication+SalesforceHybridSDK.m in your app and change the line that invokes [SFSDKAuthHelper loginIfRequired(..) to 
```
- (BOOL)sfsdk_swizzled_application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
...
if (SalesforceHybridSDKManager.sharedManager.appConfig.shouldAuthenticate) {
        [SFSDKAuthHelper loginIfRequired:^{
            [weakSelf setupRootViewController];
        }];
    } else {
       [self setupRootViewController];
    }
   return YES
}
```

**Comment by va1bhav** [comment] 2019-01-17 04:44
@trooper2013  Thank you for the input but UIApplication+SalesforceHybridSDK.m file in the app does not have function [SFSDKAuthHelper loginIfRequired(..) .

Below is the url of latest file in your repository. Please let me know if some other file is to be referred here.

https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/master/src/ios/classes/UIApplication%2BSalesforceHybridSDK.m

**Comment by va1bhav** [comment] 2019-01-17 04:53
@trooper2013 File this change is to be made is AppDelegate+SalesforceHybridSDK.m
This solves the issue for now but it needs to updated in next version of SDK. 

Also, I am planning to update from SDK 5.0.0  to SDK 7.0.0 for Android today, will keep you posted if the issue exists in android too.

**Comment by trooper2013** [comment] 2019-01-17 04:57
@va1bhav Sorry I meant to paste in  AppDelegate+SalesforceHybridSDK.m Glad it works for you. We will address it as a bug.

**Comment by wmathurin** [comment] 2019-01-17 22:23
Fix will be in next release 7.1 (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/26).

**Closed by wmathurin** 2019-01-17 22:23 UTC
Labels: bug

**Comment by wmathurin** [comment] 2019-01-24 22:36
We decided to change loginIfRequired to check shouldAuthenticate in our next release (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2756) so that work around won't be needed anymore then (but it won't hurt if you leave it).

**Comment by va1bhav** [comment] 2019-01-25 06:40
Thanks for the update @wmathurin!
