### ISSUE TITLE
unable to install pluguin

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#492] opened 2020-01-08 06:19 UTC
I tried to execute forcehybird create, which is successful. After that i removed the plugin by executing cordova plugin remove com.salesforce

Then i tried to add it back
 
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force
has no response on the terminal and the plugin is not getting installed

Node JS Version: 12.14.0
NPM version: 6.13.4
Cordova version: 9.0.0
forcehybrid version: 8.0.0

**Comment by wmathurin** [comment] 2020-01-08 18:44
Could you try with cordova CLI 8.1.2 ?

**Comment by sarathi0333** [comment] 2020-01-09 06:19
Hi @wmathurin . i tried with Cordova CLI 8.1.2 as advised. But still it doesn't work.

**Comment by wmathurin** [comment] 2020-01-09 07:12
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/493

**Comment by wmathurin** [comment] 2020-01-09 07:12
Let's continue discussing on the other issue.

**Closed by wmathurin** 2020-01-09 07:12 UTC
