### ISSUE TITLE
 User opens application and sees Salesforce Home page

### ISSUE THREAD

**Issue by EngelNick** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#567] opened 2021-12-30 15:51 UTC
Hi
We have an interesting issue with an application. By some reason, sometimes when the user tries to login to an application, instead of getting the AuthCredentials and navigating back to the application the SDK is opening the Salesforce home page.
The only workaround is to re-install the app.

Do you have any information about this issue?
Some examples in the attachments
![MicrosoftTeams-image (20) (1)](https://user-images.githubusercontent.com/18399842/147767200-433e52d8-05ab-4ee2-9306-e2cd46e8d1c9.png)
<img width="1306" alt="Screenshot at Dec 30 17-50-44" src="https://user-images.githubusercontent.com/18399842/147767209-887d4f25-16ef-4912-80cf-37d4501d9d6a.png">

**Comment by MattSynaptic** [comment] 2022-03-29 14:46
I've seen that several times as well. Generally if you swipe the app closed and re-open, it prompts you to log in again and it works. So there is a work around but it is horrible user experience that should be fixed because our customers complain about it a lot.

**Comment by gkotula** [comment] 2022-08-25 22:16
Hi all, a little more information would greatly help diagnosing this issue.  Are you using SSO to authenticate your users, or is this occurring with username/password logins as well?  When you catch this again, capturing the logs through your IDE and sharing them will help a lot.  Finally, is this only happening on iOS, or are you observing it on Android as well?

**Comment by wmathurin** [comment] 2023-06-29 23:52
Closing as this issue. It's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3388.

**Closed by wmathurin** 2023-06-29 23:52 UTC
