### ISSUE TITLE
Index issue with null property in Android

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#239] opened 2016-11-11 10:14 UTC
Hi Team,

We met another Smartstore index issue that it seems a string 'null' is stored in the index instead of null in Android when a property is null. For example:

Registered Soup User:
[
{
    'path': 'id',
    'type': 'string'
},
{
    'path': 'name',
    'type': 'string'
}]

Insert the following data:
[
    {id: 1, name: null},
    {id: 2}
]

When querying all User records:

In iOS, it returns the following:
{id: 1, name: null}
{id: 2, name: null}

in Android, it returns the following:
{id: 1, name: "null"} // ERROR: This is an issue because it returns a string of 'null'.
{id: 2, name: null}

So there is a problem when querying null value in Android. It'd be appreciated if anyone could take a look on this? Thanks.

**Comment by huminzhi** [comment] 2016-11-30 23:22
@wmathurin  this seems a valid bug?

**Comment by wmathurin** [comment] 2016-11-30 23:47
Try to set JSONObject.NULL instead of null
See http://stackoverflow.com/questions/13613754/how-do-you-set-a-value-to-null-with-org-json-jsonobject-in-java

**Comment by lingjunjiang** [comment] 2016-12-01 03:21
@wmathurin Thanks. However, the problem is that we get the data from salesforce which returns null of some fields. In this case, does that mean we need to iterate each record and check each field and substitute with JSONObject.NULL if the field is null? In my opinion, this would be in low performance especially it is not needed in iOS. Though we could check if it is in iOS, then don't need to do the substitution, but this leads to violate independent platform principal. So I was wondering if it would be possible to do this on the lower level so that client app doesn't need to even think of this issue?

@huminzhi FYI.

**Comment by wmathurin** [comment] 2016-12-01 23:53
Null are properly handled on both platforms.

For instance on Android, If I start with {id:1, name:null} in JavaScript.
I end up with the JSONObject that has 'd:1 and name:JSONObject.NULL. (In the debugger it prints out as "null" but if you .equals("null) it will say false, and if you == JSONObject.NULL it will say true).
Then if I save that object in SmartStore and later retrieve it, the name is still JSONObject.NULL and passed back to javascript I get back {id:1, name:null} as expected.

How are you querying back the records? How is it that name appears for id:2? What kind of query spec are you using?

**Comment by wmathurin** [comment] 2016-12-02 00:58
We will look into it. Thanks for reporting the issue.

**Comment by lingjunjiang** [comment] 2016-12-02 02:23
Thanks @wmathurin

**Comment by wmathurin** [comment] 2016-12-02 05:19
The bug has been addressed in the unstable branch for our upcoming release 5.0.
We are planning to release it very soon.

**Closed by wmathurin** 2016-12-02 05:19 UTC
Labels: bug

**Comment by sevem** [comment] 2016-12-02 09:38
@wmathurin @huminzhi the index is created from the mobile sdk. So I see no possibility and also no sense to fix the "null" in the created index fields after mobile sdk is done. The "null" values are not caused by our implementation in the app
