### ISSUE TITLE
Android Push Notifications not working.

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#497] opened 2020-01-23 16:58 UTC
Apologies in advance if this should be on the `SalesforceMobileSDK-Android` project.

I've created a new hybrid_remote project with `forcehybrid`.  I'm trying to replace an older app the used GCM, so I created an FCM project from the my GCM project.  I've got the "sender Id" setup in my bootconfig.json.  My connected app has the correct server key set, but I cannot get push notifications.  Specific observed behavior:

1.  When I run the app in the emulator, it is definitely registering with SF for the push notification; if I go to the Connected App and choose "send test notification", the Recipient Chooser shows a new registration for my app.  Sending a test notification provides no errors, but nothing appears in the emulator.  I have confirmed that my emulator targets Google APIs.
2.  When I run the app on device, it is not registering with SF, as I cannot see a new registration in the Test Notification recipient chooser.
3.  When I send a notification from Apex, I can see in the logs that it is sent, and no errors are thrown. Also, my code sends a iOS push and an Android push; the iOS push causes a log event "PUSH_NOTIFICATION_NO_DEVICES" with my iOS connected app's name, but nothing similar for the Android connected app; I'm assuming that's because the emulator is registered for the notification so it is getting set to google.
4.  I've tried sending a message from Firebase Console; when I set the target to my app, I get a message that 0 users are registered to receive the notification, even though the emulator is running the app.  I've accessed FCM diagnostics in the emulator and can see it is connected.

I am out of ideas.  How can I debug that fact that the device doesn't appear to be registering (not appearing in the Test Notification recipient chooser)?  Why isn't the emulator getting messages, even though it does appear in the Test Notification recipient chooser?

**Comment by bhariharan** [comment] 2020-01-23 17:05
@jclark-dot-org Thanks for the detailed breakdown of the issue. Here's what I recommend to narrow down the issue (I'm going to assume you're on `Mobile SDK 8.0`, i.e. the latest):
- Set a breakpoint [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java#L301), and verify that the response indicates success, and `id` is a valid entity ID returned from the service, i.e. it is not null.
- If there's an error response here, that means the registration failed.
- Set a breakpoint [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationDecryptor.java#L62) and sent a test notification.
- If the breakpoint gets hit, the test notification was delivered to the device. You can then step over code to see why it's not being deciphered properly, and narrow down the issue.
- If the breakpoint does not get hit, that means the notification didn't get delivered, which could indicate some configuration issue, either on the connected app or `Firebase`. We can eliminate client side issues at that point.

**Comment by jclark-dot-org** [comment] 2020-01-29 21:47
@bhariharan Thanks for debugging pointers, and sorry for the delayed response.  I followed your instructions (I am on `Mobile SDK 8.0`), and found the following:
* the first breakpoint, in `registerSFDCPushNotification()` fired, showed success, and produced a valid ID (of type `MobilePushServiceDevice`)
* the second breakpoint, in `onPushMessageReceived()`, also fired, and the `message.getData()` showed the correct payload, so the issue must be client side
* `salesforceSDKManager.getInstance().getPushNotificationReceiver()` is returning null.

Since my app is Remote Hybrid, that let me to attaching the chrome debugger to see what happened when I call `cordova.require("com.salesforce.util.push").registerPushNotificationHandler(...)`.  I found this was failing with the message "PushPlugin not found. Please install the plugin from https://github.com/phonegap/phonegap-plugin-push."

**Note:** Up to this point I hadn't really looked at the JS console for the Cordova code, since even with the app not running, no push notification ever appeared on screen in the app.  After watching in the debugger through several scenarios, I'm guessing that on Android, the app code always gets invoked before the user is notified on screen?  At any rate, seeing the breakpoints firing pointed me in the right direction.

I had previously installed `phonegap-plugin-push`, although not from github, as I had always used a push plugin in older SDK projects.  While troubleshooting the issue, I noticed that the SDK docs don't mention needing a push plugin, so I ended up removing it.  Based on the error message, I installed it via github url (`cordova plugin add https://github.com/phonegap/phonegap-plugin-push`) and then re-installed the SF plugin per the SDK docs (`cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force`).  Unfortunately, the build now fails.  From the command line I get this: 

    /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
    Note: /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/model/InstrumentationEventBuilder.java uses or overrides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    /Users/jclark/.gradle/caches/transforms-2/files-2.1/cc6fccc44380da53d1c5f0448200394f/firebase-common-19.2.0/jars/classes.jar(com/google/firebase/FirebaseApp.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
    /Users/jclark/.gradle/caches/transforms-2/files-2.1/ed49461a99a2c8376f0de35db29a5eaf/firebase-iid-20.0.1/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
    /Users/jclark/.gradle/caches/transforms-2/files-2.1/ed49461a99a2c8376f0de35db29a5eaf/firebase-iid-20.0.1/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    3 warnings
    Note: /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java uses or overrides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushInstanceIDListenerService.java:9: error: cannot find symbol
    import com.google.firebase.iid.FirebaseInstanceIdService;
                                  ^
      symbol:   class FirebaseInstanceIdService
      location: package com.google.firebase.iid
    /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushInstanceIDListenerService.java:15: error: cannot find symbol
    public class PushInstanceIDListenerService extends FirebaseInstanceIdService implements PushConstants {
                                                       ^
      symbol: class FirebaseInstanceIdService
    /Users/jclark/.gradle/caches/transforms-2/files-2.1/ed49461a99a2c8376f0de35db29a5eaf/firebase-iid-20.0.1/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
    /Users/jclark/.gradle/caches/transforms-2/files-2.1/ed49461a99a2c8376f0de35db29a5eaf/firebase-iid-20.0.1/jars/classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
    /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushInstanceIDListenerService.java:18: error: method does not override or implement a method from a supertype
        @Override
        ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: /Users/jclark/Documents/workspace/MobileApp/app/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushPlugin.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    3 errors
    2 warnings

    FAILURE: Build failed with an exception.

But in Android Studio I get 51 errors accross 5 source files, including `error: cannot find symbol class NotificationCompat` and `error: package android.support.v4.app.NotificationCompat does not exist`. 

Assuming this is a problem with the current github version, I rolled back to my prior pushplugin build (which was set up using `cordova plugin add phonegap-plugin-push`).  Now when I call:

    cordova.require("com.salesforce.util.push").registerPushNotificationHandler(
        function(message) { // push handler},
        function(error) {
            console.log('***received push notification error: ');
            console.log(error)
        });

The error handler is getting invoked; I see the following in the console:

![Screen Shot 2020-01-29 at 4 39 40 PM](https://user-images.githubusercontent.com/2294694/73399887-0561d480-42b6-11ea-9ab2-5f60729cd2b6.png)

At this point I'm stuck.  It's not clear to me what is causing the 'class not found' error being reported by my `console.log(error)`, and the error from `com.salesforce.util.push.js:66` is an empty object.

**Comment by bhariharan** [comment] 2020-02-04 16:57
@jclark-dot-org The compilation error messages seems to be in `PushPlugin` land. Perhaps you could file an issue with them? The issues you're facing appear to be outside Mobile SDK. You could add a native handler for the incoming push notifications like our native apps, and avoid using `PushPlugin` if you choose to. That might be the easiest path forward.

**Comment by wmathurin** [comment] 2020-07-08 22:28
From the conversation, it looks like the issue is outside the Mobile SDK. Closing issue.

**Closed by wmathurin** 2020-07-08 22:28 UTC
