### ISSUE TITLE
Smartstore issue with Mobile SDK 4.3 with Android platform

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#217] opened 2016-08-23 10:33 UTC
Dear friends,

I upgrade my apps to Mobile SDK 4.3, all works fine in iOS. However, I have now Smartstore issues in Android.

The apps work fine in Android if not using Smartstore. When using Smartstore, I got the following error messages in the console.

08-23 18:14:08.431 5800-9476/com.xx.xx.xx W/SmartStorePlugin.execute: get field slot from row 0 col 0 failed
                                                                             java.lang.IllegalStateException: get field slot from row 0 col 0 failed
                                                                                 at net.sqlcipher.CursorWindow.getString_native(Native Method)
                                                                                 at net.sqlcipher.CursorWindow.getString(CursorWindow.java:385)
                                                                                 at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                                                 at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                                                 at com.salesforce.androidsdk.smartstore.store.SmartStore.query(SmartStore.java:798)
                                                                                 at com.salesforce.androidsdk.smartstore.store.StoreCursor.getData(StoreCursor.java:94)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.runQuery(SmartStorePlugin.java:437)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.querySoup(SmartStorePlugin.java:400)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$700(SmartStorePlugin.java:59)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:144)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
08-23 18:14:08.431 5800-9476/com.xx.xx.xx D/SmartSTorePlugin.execute: Total time for pgQuerySoup->229
08-23 18:14:08.441 5800-5800/com.xx.xx.xx I/chromium: [INFO:CONSOLE(43)] "TIMING com.salesforce.smartstore:pgQuerySoup failed", source: file:///android_asset/www/plugins/com.salesforce/www/com.salesforce.util.exec.js (43)

I found the Sqlite is upgraded to 3.5.2 in SDK 4.3 where it was 3.4 in SDK 4.2, will this introduced the problem? And I'm also not sure if I'm the only one having this problem. My device is Samsung Galaxy S5, Android 6.0.1.

Thanks for any reply.

**Comment by lingjunjiang** [comment] 2016-08-23 10:37
Smarestore worked well in Android platform with SDK 4.2 previously.

**Comment by sevem** [comment] 2016-08-23 12:41
same issue with 4.3 on Android Emulator and on a Nexus 5X with Android 6.0.1. But I think this is a tricky problem. Some smartstore functionalities works fine. The error occurs when I execute one query


 var querySpec = navigator.smartstore.buildAllQuerySpec('xyz', null, 100000000);
navigator.smartstore.querySoup('_someSoup', querySpec, function (cursor) { ....

then I got this error

```
08-23 14:29:07.597 16074-16148/com.oinio.linde.isw.dev I/SmartStorePlugin.execute: action: pgQuerySoup, jsVersion: 4.3.0
08-23 14:29:07.598 16074-16148/com.oinio.linde.isw.dev D/SmartSTorePlugin.execute: Main thread time for pgQuerySoup->1
08-23 14:29:07.784 16074-16080/com.oinio.linde.isw.dev W/art: Suspending all threads took: 7.685ms
08-23 14:29:07.809 16074-26376/com.oinio.linde.isw.dev W/SmartStorePlugin.execute: get field slot from row 0 col 0 failed
                                                                                   java.lang.IllegalStateException: get field slot from row 0 col 0 failed
                                                                                       at net.sqlcipher.CursorWindow.getString_native(Native Method)
                                                                                       at net.sqlcipher.CursorWindow.getString(CursorWindow.java:385)
                                                                                       at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                                                       at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                                                       at com.salesforce.androidsdk.smartstore.store.SmartStore.query(SmartStore.java:798)
                                                                                       at com.salesforce.androidsdk.smartstore.store.StoreCursor.getData(StoreCursor.java:94)
                                                                                       at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.runQuery(SmartStorePlugin.java:437)
                                                                                       at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.querySoup(SmartStorePlugin.java:400)
                                                                                       at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$700(SmartStorePlugin.java:59)
                                                                                       at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:144)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)
08-23 14:29:07.809 16074-26376/com.oinio.linde.isw.dev D/SmartSTorePlugin.execute: Total time for pgQuerySoup->212
08-23 14:29:08.270 16074-16074/com.oinio.linde.isw.dev I/chromium: [INFO:CONSOLE(43)] "TIMING com.salesforce.smartstore:pgQuerySoup failed", source: file:///android_asset/www/plugins/com.salesforce/www/com.salesforce.util.exec.js (43)
```

**Comment by huminzhi** [comment] 2016-08-23 23:40
@sevem just to confirm, so it seems only happens when 'xyz' (in your example) is not a valid field?

**Comment by huminzhi** [comment] 2016-08-24 18:23
@lingjunjiang @sevem Just wonder if the field here is valid or not?

**Comment by huminzhi** [comment] 2016-08-24 21:55
@lingjunjiang @sevem I tried hard to reproduce this issue with either fresh install or upgrade path.. but cannot reproduce.. so it seems hitting some system scalability issue: http://stackoverflow.com/questions/6669364/java-lang-illegalstateexception-get-field-slot-from-row-0-col-0-failed?

**Comment by sevem** [comment] 2016-08-24 22:25
@huminzhi yes this is a valid field. The query is created dynamically by our core components. In other projects, exact the same functionality works without a problem. And we had no problems with version 4.2. And regarding to optimize our query. Exact the same code with exact the same records worked fine with 4.2. Update to 4.3 and we had this problem. I will try to make some more tests to give you more detailed informations. But unfortunately I will have less time in the next weeks

**Comment by huminzhi** [comment] 2016-09-28 18:54
@sevem @lingjunjiang Sorry to get back late on this. After discussion, we think it's data related issue (some field is exceed 1M somehow).. Just wonder if you can try to change the query to 
var querySpec = navigator.smartstore.buildAllQuerySpec('xyz', null, 10); or 
var querySpec = navigator.smartstore.buildAllQuerySpec('xyz', null, 100;
Just to see if we still hit this issue, thus we can understand the nature of this issue more.. Thank you!

**Comment by sevem** [comment] 2016-09-30 14:17
@huminzhi unfortunately we've already tried that. Issue still exists

**Comment by sevem** [comment] 2016-10-04 08:55
@huminzhi I've tested the version 4.3 once again. On a Android tablet, smartphone and in the emulator. I've attached the stacktraces. With MobileSDK 4.2 I have no problems

[stacktrace_emulator.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/507980/stacktrace_emulator.txt)
[stacktrace_smartphone.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/507981/stacktrace_smartphone.txt)
[stacktrace_tablet.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/507982/stacktrace_tablet.txt)

**Comment by wmathurin** [comment] 2016-10-06 20:36
In the tablet stacktrace, there is a out of memory exception. Did you get that as well with the phone or emulator?

Could you give us a sense of what the data looks like the number of rows, columns (i.e. the number of index specs on the soup) and average size of the JSON blobs you have inserted in the soup?

**Comment by sevem** [comment] 2016-11-09 19:46
@wmathurin sorry for the delay. I'm really busy at the moment. But I will try to give you your requested information in the next days

**Comment by sevem** [comment] 2016-12-12 17:11
@wmathurin once again sorry for the delay. I don't think that this is a out of memory problem. I've retested that. Same error as in Lingjun's initial post

`I/art: Background partial concurrent mark sweep GC freed 99644(3MB) AllocSpace objects, 33(4MB) LOS objects, 28% free, 10MB/14MB, paused 580us total 103.269ms
W/SmartStorePlugin.execute: get field slot from row 0 col 0 failed
                                                                               java.lang.IllegalStateException: get field slot from row 0 col 0 failed
                                                                                   at net.sqlcipher.CursorWindow.getString_native(Native Method)
                                                                                   at net.sqlcipher.CursorWindow.getString(CursorWindow.java:385)
                                                                                   at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                                                   at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                                                   at com.salesforce.androidsdk.smartstore.store.SmartStore.query(SmartStore.java:798)
                                                                                   at com.salesforce.androidsdk.smartstore.store.StoreCursor.getData(StoreCursor.java:94)
                                                                                   at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.runQuery(SmartStorePlugin.java:437)
                                                                                   at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.querySoup(SmartStorePlugin.java:400)
                                                                                   at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$700(SmartStorePlugin.java:59)
                                                                                   at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:144)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
D/SmartSTorePlugin.execute: Total time for pgQuerySoup->123
I/chromium: [INFO:CONSOLE(43)] "TIMING com.salesforce.smartstore:pgQuerySoup failed", source: file:///android_asset/www/plugins/com.salesforce/www/com.salesforce.util.exec.js (43)`

Again tested with 4.3.1. The problem occurs when we try to save a describeSObject of an Account in the smartstore. The JSON of the describe is about 800KB. I will also test this issue with the latest unstable branch

**Comment by wmathurin** [comment] 2016-12-12 19:37
Maybe you are hitting the 1MB cursor limit (see http://stackoverflow.com/questions/17331978/sqlite-cursor-limit-1mb).
If you are storing large JSON objects in SmartStore, you might want to consider using "external storage" (a new feature in SmartStore introduced in 4.3). For more information, check out https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_external_storage.htm

**Comment by sevem** [comment] 2016-12-13 07:15
@wmathurin with version 4.2 we do not have any issues. And I guess the 1MB limit also exists in older versions

**Comment by sevem** [comment] 2016-12-13 13:03
@wmathurin tested with the new version 5.0. Same problem. But I think I found an potential issue in our implementation. The problem is not the insert of the single big describeSObject or describeLayout. The problem seems to be, as you mentioned, the way we load them from the smartstore. We have about 5 to 10 describeLayout in one soup. And we load them at once. I think this is the cause of the problem. Only two such big describes and we are hitting the 1MB limit. Strange is, same code and no issues with Mobile SDK 4.2. I will investigate that and also take a look on your suggested external storage

@lingjunjiang fyi

**Comment by sevem** [comment] 2017-01-10 14:07
@wmathurin I will try to use the external storage to solve our problem. Unfortunately the documentation for javascript is not really clear. Do you have a hint or a short code snippet for me how to use external storage in a hybrid app?

**Comment by wmathurin** [comment] 2017-01-10 17:24
You want to use registerWithSoupSpec (see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_external_registration.htm).

A soup spec is basically a dictionary with name and features. For external storage, you want the "externalStorage" feature.

So your register soup call should look like:
```JavaScript
navigator.smartstore.registerWithSoupSpec({name:soupName, features:["externalStorage"]}, indexSpecs, ...)
```

**Comment by sevem** [comment] 2017-01-11 07:02
@wmathurin cool. thx ... features:["externalStorage"] was missing for me. This is not included in the official documentation.

**Comment by sevem** [comment] 2017-01-11 10:32
@wmathurin @lingjunjiang using externalStorage solves our problem. So I think we can close this issue. But I have three more questions

1. are externalStorage soups global soups or does every user have his own soup? I hope that externalStorage soups are "private" soups. Otherwise this is not an option for us
2. are there any limitations or risk in using externalStorage we should know?
3. does is the externalStorage handling identical to normal soups? So no other changes necessary in our current implementation?

**Comment by wmathurin** [comment] 2017-01-11 15:10
1. The storage type is unrelated to whether the soup is global or not. Any soups can use external storage. By the way, you can also use the alterSoup API to change a soup storage type.

2/3. JSON1 indexes are not allowed on a soup using external storage. Otherwise everything behaves the same / all operations are supported. 

JSON1 indexes were introduced in 4.2 and are leveraging the JSON1 extension in SQLite. When we started SmartStore, SQLite had no support for JSON: you couldn't index a JSON object or query by field within JSON object. In late 2015/early 2016 SQLite/SQLCipher added the JSON1 extension which does just that. We exposed that in SmartStore. But of course, it can only work when the database is given the JSON objects (which we don't do with externally stored soup). 

4. We always had a directory structure with folders per users and a global folder to store any app files (e.g. the database files). Next to the database file, we added a folder to hold the JSON blobs. The JSON blob files are uniquely named using the soup entry id. For more information, you can look at the code on [iOS](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SmartStore/SmartStore/Classes/SFSmartStore.m#L743) and [Android](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java#L472).

**Closed by wmathurin** 2017-01-11 15:10 UTC
Labels: bug

**Comment by sevem** [comment] 2017-01-11 15:26
@wmathurin thanks for your answer. I want to clarify two questions just to ensure that I understand everything correctly

1. if a external storage is unrelated to global or not, nevertheless every user has his own soup? Is that correct? In some of my projects the users are sharing the same device. So we have multiple users using the same app. We have to ensure that every user also has his own external storage. With "normal" soups we have this behavior isGlobal = false

2. if I can use alterSoup to change the storage type, that means that I can change the type to external storage on the fly? So it is possible to change the storage type in an running app with a existing soup?

**Comment by wmathurin** [comment] 2017-01-11 15:31
1. Global or not is a property of the store (the database in other words) and external or internal storage is a property of the soup (the table). You can have externally stored soups in the global store and in the user store. The soup storage type has no impact on whether the store is public or private.
2. Yes you can. However, alterSoup could take a while to run if you have a lot of data. During that time, you won't be able to use the store. You should test with your data and see if the time it takes and the user experience resulting from it are acceptable for your application.

**Comment by lingjunjiang** [comment] 2017-01-12 02:27
Sounds pretty cool! Thanks @wmathurin @sevem
